name: network_graph
version: 0.1.1+4
publish_to: https://onepub.dev/api/sxssdavuhn/
repository: https://github.com/herrytco/flutter_network_graph
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  test: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
